Cargadores/Controllers/PrestamosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Cargadores;

namespace Cargadores.Controllers
{
    public class PrestamosController : Controller
    {
        private CargadoresEntities db = new CargadoresEntities();

        // GET: Prestamos
        public ActionResult Index()
        {
            var prestamos = db.Prestamos.Include(p => p.Cargadores).Include(p => p.Usuarios).Include(p => p.Usuarios1);
            return View(prestamos.ToList());
        }

        // GET: Prestamos/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Prestamos prestamos = db.Prestamos.Find(id);
            if (prestamos == null)
            {
                return HttpNotFound();
            }
            return View(prestamos);
        }

        // GET: Prestamos/Create
        public ActionResult Create()
        {
            ViewBag.IdCargador = new SelectList(db.Cargadores, "IdCargador", "IdCargador");
            ViewBag.IdUsuarioDueño = new SelectList(db.Usuarios, "IdUsuario", "Nombre");
            ViewBag.IdUsuarioPrestamo = new SelectList(db.Usuarios, "IdUsuario", "Nombre");
            return View();
        }

        // POST: Prestamos/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdUsuarioDueño,IdCargador,IdUsuarioPrestamo,Fecha")] Prestamos prestamos)
        {
            if (ModelState.IsValid)
            {
                db.Prestamos.Add(prestamos);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.IdCargador = new SelectList(db.Cargadores, "IdCargador", "IdCargador", prestamos.IdCargador);
            ViewBag.IdUsuarioDueño = new SelectList(db.Usuarios, "IdUsuario", "Nombre", prestamos.IdUsuarioDueño);
            ViewBag.IdUsuarioPrestamo = new SelectList(db.Usuarios, "IdUsuario", "Nombre", prestamos.IdUsuarioPrestamo);
            return View(prestamos);
        }

        // GET: Prestamos/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Prestamos prestamos = db.Prestamos.Find(id);
            if (prestamos == null)
            {
                return HttpNotFound();
            }
            ViewBag.IdCargador = new SelectList(db.Cargadores, "IdCargador", "IdCargador", prestamos.IdCargador);
            ViewBag.IdUsuarioDueño = new SelectList(db.Usuarios, "IdUsuario", "Nombre", prestamos.IdUsuarioDueño);
            ViewBag.IdUsuarioPrestamo = new SelectList(db.Usuarios, "IdUsuario", "Nombre", prestamos.IdUsuarioPrestamo);
            return View(prestamos);
        }

        // POST: Prestamos/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdUsuarioDueño,IdCargador,IdUsuarioPrestamo,Fecha")] Prestamos prestamos)
        {
            if (ModelState.IsValid)
            {
                db.Entry(prestamos).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.IdCargador = new SelectList(db.Cargadores, "IdCargador", "IdCargador", prestamos.IdCargador);
            ViewBag.IdUsuarioDueño = new SelectList(db.Usuarios, "IdUsuario", "Nombre", prestamos.IdUsuarioDueño);
            ViewBag.IdUsuarioPrestamo = new SelectList(db.Usuarios, "IdUsuario", "Nombre", prestamos.IdUsuarioPrestamo);
            return View(prestamos);
        }

        // GET: Prestamos/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Prestamos prestamos = db.Prestamos.Find(id);
            if (prestamos == null)
            {
                return HttpNotFound();
            }
            return View(prestamos);
        }

        // POST: Prestamos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Prestamos prestamos = db.Prestamos.Find(id);
            db.Prestamos.Remove(prestamos);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Cargadores/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Cargadores</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Cargadores", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li>@Html.ActionLink("Acerca de", "About", "Home")</li>
                    <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Usuarios", "Index", "Usuarios")</li>
                    <li>@Html.ActionLink("Cargadores", "Index", "Cargadores")</li>
                    <li>@Html.ActionLink("Préstamos", "Index", "Prestamos")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>